apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lint
spec:
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/upslopeio/lint-markdown-files.git
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data
  workspaces:
  - name: pipeline-shared-data