apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  generateName: lint-
spec:
  pipelineRef:
    name: lint
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi